lib/jekyll-github-metadata/ghp_metadata_generator.rb
spec/test-site/_config.yml

GHPMetadataGenerator: Don't overwrite site.github if it's already set.

---

README.md
lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/ghp_metadata_generator.rb
lib/jekyll-github-metadata/pages.rb
lib/jekyll-github-metadata/repository.rb
spec/ghp_metadata_generator_spec.rb
spec/github_metadata_spec.rb
spec/integration_spec.rb
spec/spec_helper.rb

Fixes #28
- `PAGES_REPO_NWO` overrides `site.repository`
- `JEKYLL_BUILD_REVISION` overrides `site.github.build_revision`
- Added 2 missing fields

Bring this gem up-to-date with latest GitHub Pages metadata

---

lib/jekyll-github-metadata/client.rb
spec/client_spec.rb

Instead of responding to _every_ client call, whitelist only a few.

Client: whitelist certain Octokit::Client methods

---

lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/repository.rb

This moves any fields which are purely client-generated into memoized fields on `Repository`.

All values should have a repository field

---

lib/jekyll-github-metadata.rb
spec/integration_spec.rb

It should be `dotcom`, not `production`, for example.

site.github.environment should be the same as site.github.pages_env

---

README.md

This PR removes the "first a very special..." line from the readme, now that GitHub's maintaining/contributing to the plugin.

Remove thank you from readme

---

lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/client.rb
spec/integration_spec.rb

Right now, if the client makes a call to the same endpoint, but for two different domains (or the same endpoint, but with different arguments), it will return the first, cached result.
That's because the client caches on the method name, irregardless of arguments.
This PR creates a cache hash (rather than using instance variables), and computes a unique key, using SHA1, which I guessed was the cheapest way to generate a unique, consistent hash from the method name + args (knowing that the args may be long).
Thoughts on this approach?
Fixes https://github.com/jekyll/github-metadata/issues/39

Properly determine project page domain by breaking the cache on different args

---

lib/jekyll-github-metadata/ghp_metadata_generator.rb
spec/ghp_metadata_generator_spec.rb

When debugging output would be helpful...
[If the plugin isn't safe, it won't be included in the set](https://github.com/jekyll/jekyll/blob/v3.0.3/lib/jekyll/site.rb#L292-L305).

Mark the generator as safe so in safe mode it'll work

---

.travis.yml
lib/jekyll-github-metadata/ghp_metadata_generator.rb
spec/ghp_metadata_generator_spec.rb
spec/spec_helper.rb

Fixes #44
@parkr any idea how to properly mock the `git_remote_url` method?

Use git remote url to determine nwo

---

lib/jekyll-github-metadata/ghp_metadata_generator.rb

Hi,
see https://github.com/jekyll/jekyll/issues/4748 for more information about the issue.
**Before**
**After**

make empty string fallback for missing git remote

---

README.md
lib/jekyll-github-metadata/ghp_metadata_generator.rb

Refactor some of the git things & better docs

---

lib/jekyll-github-metadata.rb

Hi,
i didn't know if tests are needed for this because i think they would only test the behavior already tested in the dotenv repository. Also i'm not sure if i should add something to the README about this.

Load ENV via dotenv if available

---

.travis.yml
jekyll-github-metadata.gemspec
lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/ghp_metadata_generator.rb
lib/jekyll-github-metadata/metadata_drop.rb
script/test
spec/ghp_metadata_generator_spec.rb
spec/github_metadata_spec.rb
spec/integration_spec.rb
spec/metadata_drop_spec.rb
spec/repository_spec.rb
spec/spec_helper.rb

This PR uses a `Jekyll::Drops::Drop` to generate all of the repository information **only when requested**.
For example:
```text
~/jekyll/jekyll/site#master$ PAGES_PREVIEW_HTML_URL=true JEKYLL_GITHUB_TOKEN=$(cat ~/.token) be jekyll serve --verbose --trace | grep GitHub
GitHub Metadata: Initializing...
```
No calls.
```text
~/jekyll/jekyll/site#master$ PAGES_PREVIEW_HTML_URL=true JEKYLL_GITHUB_TOKEN=$(cat ~/.token) be jekyll serve --verbose --trace | grep GitHub
GitHub Metadata: Initializing...
GitHub Metadata: Generating for jekyll/jekyll
GitHub Metadata: Calling @client.pages("jekyll/jekyll", {:accept=>"application/vnd.github.mister-fantastic-preview+json"})
```
```text
GitHub Metadata: Initializing...
GitHub Metadata: Generating for jekyll/jekyll
GitHub Metadata: Calling …
```

Only determine repo when data is requested using a Drop

---

.travis.yml
lib/jekyll-github-metadata/metadata_drop.rb
spec/metadata_drop_spec.rb

Handle dots in repository names when parsing from Git remote output

---

lib/jekyll-github-metadata/repository.rb
spec/repository_spec.rb
spec/webmock/api_get_jekyll_repo_pages.json

For consistency, the `html_url` field of the pages preview API will begin returning URLs with trailing slashes in all cases. Because many sites hardcode things like `{{ page.url | prepend: site.github.url }}`, we need to maintain backwards compatibility, and have `site.github.url` continue to *not* have a trailing slash.
This PR simply strips the trailing slash from the calculated URL or API response, if it's present, so that we never have a trailing slash. Ever.

Remove trailing slash from html_url if present

---

README.md

The default value of `site.github.api_url` is `https://api.github.com`, rather than `https://api/github.com`.

Fix a typo in the documentation of `PAGES_API_URL`

---

.travis.yml
jekyll-github-metadata.gemspec

Tests on master are currently broken, and given our current set up, will always be broken when this repo has a different version number than the version used in the last release of GitHub Pages.
This PR updates the travis config to not try to build against the latest Pages gem version (which is built as part of CI upstream now).

Dont try to build with the latest released pages gem to avoid conflicts

---

.rubocop.yml
jekyll-github-metadata.gemspec
lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/client.rb
lib/jekyll-github-metadata/ghp_metadata_generator.rb
lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/pages.rb
lib/jekyll-github-metadata/repository.rb
lib/jekyll-github-metadata/repository_compat.rb
lib/jekyll-github-metadata/sanitizer.rb
lib/jekyll-github-metadata/value.rb
lib/jekyll-github-metadata/version.rb
script/test
spec/client_spec.rb
spec/ghp_metadata_generator_spec.rb
spec/github_metadata_spec.rb
spec/integration_spec.rb
spec/metadata_drop_spec.rb
spec/pages_spec.rb
spec/repository_compat_spec.rb
spec/repository_spec.rb
spec/spec_helper.rb
spec/value_spec.rb

Based off of Jekyll's Rubocop config.

Add rubocop

---

lib/jekyll-github-metadata/ghp_metadata_generator.rb
lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/repository.rb
spec/ghp_metadata_generator_spec.rb
spec/integration_spec.rb
spec/repository_spec.rb
spec/spec_helper.rb

This allows `relative_url` and `absolute_url` to "just work" in most cases, by silently setting `site.url` and `site.baseurl` if either are not already set by the user.
This is a quick spike, and could use:

Spike out setting site.url and site.baseurl

---

lib/jekyll-github-metadata/ghp_metadata_generator.rb
lib/jekyll-github-metadata/repository.rb
script/cibuild
script/fmt
spec/ghp_metadata_generator_spec.rb

@benbalter Got a problem. Right now, if you have `https://benbalter.github.io/maps/` as `site.github.url`, you get:
- `baseurl = "/maps/"` ✅ 
- `url = "https://benbalter.github.io/maps/"` ❌ 
This means `minima` [is providing bad url's](https://github.com/jekyll/minima/blob/v1.2.0/_includes/head.html#L9-L13).

Remove the `path` before setting `site.url`

---

lib/jekyll-github-metadata/metadata_drop.rb
spec/metadata_drop_spec.rb
spec/spec_helper.rb

This fixes an issue where `{{ site.github }}` doesn't expand out to all the values in the Drop.
This is controlled by `Drop#to_s` which, by default, is `self.class.name`.

Add MetadataDrop#to_s which outputs pretty JSON representation

---

jekyll-github-metadata.gemspec

v4.4.0 introduced a change where it requires preview headers for `GET /repos/o/r/pages`, which aren't required. This will break our requests to get Pages metadata, such as `cname`, `html_url`, etc.
PR which breaks it: https://github.com/octokit/octokit.rb/pull/815
PR which fixes it: https://github.com/octokit/octokit.rb/pull/822

Lock Octokit to v4.3.0

---

jekyll-github-metadata.gemspec

Reverts jekyll/github-metadata#79, but allows octokit v4.4.1 which has the fix (https://github.com/octokit/octokit.rb/pull/822).
https://github.com/octokit/octokit.rb/releases/tag/v4.4.1

Revert "Lock Octokit to v4.3.0", but disallow v4.4.0

---

.rubocop.yml
lib/jekyll-github-metadata/repository.rb
spec/repository_spec.rb
spec/webmock/api_get_jekyll_repo_pages.json

The Pages API now exposes source branch and path metadata. We should use that to build the proper zip and tar URLs so we respect the source selector.

Respect source passed from the API

---

lib/jekyll-github-metadata/client.rb

It looks scary even though it's often totally fine.

Remove log on Octokit::NotFound

---

lib/jekyll-github-metadata/ghp_metadata_generator.rb
lib/jekyll-github-metadata/pages.rb
spec/pages_spec.rb

`.configuration` gives us a way to debug our metadata fetching by showing what the Pages configuration is.
`.page_build?` gives us a different way to enable automatically setting the `site.url` and `site.baseurl` values when running in development mode.
/cc @jldec

Add .configuration and .page_build? methods to Pages

---

lib/jekyll-github-metadata/site_github_munger.rb
spec/site_github_munger_spec.rb

For use with things like Jekyll SEO Tag in default templates.

Set default site.title and site.description

---

lib/jekyll-github-metadata/metadata_drop.rb

Added via https://github.com/jekyll/github-metadata/pull/88. Users can use `site.github.latest_release.url` if they really want it, but I suspect what they want is `site.github.latest_release.html_url`. Feels silly to expose the API url as `site.github.latest_release_url`.

Remove latest release url

---

lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/repository.rb
spec/integration_spec.rb

This PR adds a `private` key to the `site.github` namespace. The value will be `true` if the repo is private, otherwise, it will be `false`. This will allow a site to know it's visibility (for example, to conditionally expose an edit button via a theme).

Expose repo visibility

---

.rspec
.rubocop.yml
lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/repository_finder.rb
lib/jekyll-github-metadata/site_github_munger.rb
lib/jekyll-github-metadata/value.rb
spec/integration_spec.rb
spec/metadata_drop_spec.rb
spec/repository_finder_spec.rb
spec/site_github_munger_spec.rb
spec/spec_helper.rb
spec/test-site/index.html
spec/value_spec.rb

A follow up to https://github.com/jekyll/github-metadata/pull/101, the title and description were only being set in production, making local previewing difficult.
This PR updates the logic to set the title and description in dev by moving the conditional statement.

Set title and description in dev

---

lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/site_github_munger.rb
spec/edit_link_tag_spec.rb
spec/site_github_munger_spec.rb
spec/spec_helper.rb

Via https://github.com/jekyll/github-metadata/pull/108#issuecomment-325817689, it appears user-supplied `site.github` values are being overwritten by drop-supplied values.
It appears in https://github.com/jekyll/github-metadata/commit/54942a488f493a346d709c208799558afc012a5a#diff-165b64b2f6bce98447b6c550f3205ad9L26, the order of the arguements passed to `Jekyll::Utils.deep_merge_hashes` were reversed since [the right overrides the left value](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/utils.rb#L39-L54).
This PR adds failing tests via a7d2b4b to ensure `site.github` is set to the expected value given different user-supplied inputs for `site.github` with d36d1af reversing the order of the arguments.
/cc @DirtyF

Allow user values to override drop-determined values

---

lib/jekyll-github-metadata/metadata_drop.rb
spec/metadata_drop_spec.rb

This is a side effect of monkey patching https://github.com/jekyll/jekyll/pull/6338 into https://github.com/jekyll/github-metadata/pull/110.
In https://github.com/jekyll/jekyll/pull/6338 the problem was that `Drop#key?` needed to call `self.class.mutable?` not `self.class.mutable`. Rather than wait on the upstream fix, I monkey patched a modified version of `key?` with that single character change. 
As it turns out, there's more wrong with `key?` in Jekyll core. If you read through the logic of:
https://github.com/jekyll/jekyll/blob/8b47fb1f7a85d518a21f5fcfd3b20df18c60bf7a/lib/jekyll/drops/drop.rb#L101-L112
You'll see that if a Drop is mutable, and the user hasn't overridden the requested key, the Drop will respond that it doesn't know anything about the key (even if it has a non-mutated …

Mutable drops should fallback to their own methods when a mutation isn't present

---

lib/jekyll-github-metadata/site_github_munger.rb
spec/site_github_munger_spec.rb

Per https://github.com/jekyll/jekyll-seo-tag/issues/238#issuecomment-328594374.

Warn and do nothing when site.name is set

---

.editorconfig

Attempt to fix EOL errors on AppVeyor

Normalize whitespace across platforms

---

lib/jekyll-github-metadata.rb

Some of the checks placed here were to support Jekyll 2.x and is no longer necessary since we're requiring `Jekyll 3.1+` now
Not sure why the following has a check since Jekyll has always had `Site` constant defined.. So leaving that as is..
https://github.com/jekyll/github-metadata/blob/2c350b2fea29ee5fe18243ff84040a755a9de508/lib/jekyll-github-metadata.rb#L37-L39

Remove redundant code

---

.travis.yml
jekyll-github-metadata.gemspec
lib/jekyll-github-metadata/repository_finder.rb
spec/repository_finder_spec.rb

The repository detection code wasn't portable to Windows.
These changes fix detection on Windows and maintain portability with other platforms.

Fixes for repository detection on Windows

---

lib/jekyll-github-metadata/pages.rb
spec/repository_spec.rb

In development mode (the default) github.com repo URLs are http,
making sites using edit-link-tag have slightly different builds in
development than on github pages (dotcom) which are also slightly
harder to test for all links being https, eg using html-proofer
with its enforce_https option, and making builds published to
non-github pages hosts have non-https links to github.com.
Trivial patch for a very mild annoyance.
The added test is somewhat contrived, because existing tests don't
trigger the behavior, running in test mode (which defaults scheme
to ssl), or hardcoding the repository url (in the edit-link-tag
test).

Make github.com repo URLs always https

---

jekyll-github-metadata.gemspec
script/console
script/console.rb

`script/console` will open a PRY session with Octokit debug output enabled and pseudo-production values as the default to help diagnose failed builds.

Add script/console to help debug

---

lib/jekyll-github-metadata/repository_finder.rb
spec/repository_finder_spec.rb

Alters the regex that extracts the org/username and repo name from the repo address based on suggestion by @benbalter, so that it can cope with repos that do not exist on github.com (e.g. GitHub Enterprise).
Adds a test for this change.
Resolves #120

Allow detecting repository on GitHub Enterprise

---

.rubocop.yml
.travis.yml
Gemfile
jekyll-github-metadata.gemspec
lib/jekyll-github-metadata.rb
lib/jekyll-github-metadata/client.rb
lib/jekyll-github-metadata/edit-link-tag.rb
lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/pages.rb
lib/jekyll-github-metadata/repository.rb
lib/jekyll-github-metadata/repository_compat.rb
lib/jekyll-github-metadata/repository_finder.rb
lib/jekyll-github-metadata/sanitizer.rb
lib/jekyll-github-metadata/site_github_munger.rb
lib/jekyll-github-metadata/value.rb
lib/jekyll-github-metadata/version.rb
script/console.rb
spec/client_spec.rb
spec/pages_spec.rb
spec/repository_compat_spec.rb
spec/repository_finder_spec.rb
spec/repository_spec.rb
spec/site_github_munger_spec.rb
spec/spec_helpers/fixture_helper.rb
spec/spec_helpers/web_mock_helper.rb
spec/value_spec.rb

Each commit describes the change!

Update CI settings and use rubocop-jekyll

---

lib/jekyll-github-metadata/client.rb
lib/jekyll-github-metadata/metadata_drop.rb
lib/jekyll-github-metadata/repository.rb
spec/spec_helpers/integration_helper.rb

Fixes #149.
Tested locally for a User object, captured everything I was interested in (full name, email, company, bio, ...)
/cc @parkr @benbalter 
Thanks!
Filipe

Expose User/Org information under site.github.owner

---

lib/jekyll-github-metadata/owner.rb
lib/jekyll-github-metadata/repository.rb
lib/jekyll-github-metadata/sanitizer.rb
spec/integration_spec.rb
spec/spec_helpers/integration_helper.rb

Before: you'd get `site.owner` as a JSON-encoded String.
After: you get `site.owner` as a Hash. Now you can dereference values!

site.owner should be a Hash in the final value

---

lib/jekyll-github-metadata/owner.rb
spec/test-site/index.html
spec/test-site/subvalues.txt

Otherwise `{{ site.github.owner }}` fails.

Add Owner#to_liquid

---

.travis.yml
jekyll-github-metadata.gemspec

Allows the plugin to be used with Jekyll 3.x or 4.x (assuming tests pass)

Lessen Jekyll dependency

---

lib/jekyll-github-metadata/repository.rb
script/webmock-repopulate
spec/spec_helpers/web_mock_helper.rb

Include the topics property in the repository results using the `application/vnd.github.mercy-preview+json` media type.

Enable support for `topics` property

---

docs/README.md
docs/site.github.md

The GitHub Help Documentation has been updated and doesn't list these fields anymore. Since it belongs to this project, it makes sense to list them all here.
Much of this text is [borrowed directly from the GitHub Help Documentation](https://web.archive.org/web/20190616095556/https://help.github.com/en/articles/repository-metadata-on-github-pages). Credit goes to the wonderful Documentation team at GitHub for writing this up!

List the fields this repo generates for site.github

---

History.markdown
lib/jekyll-github-metadata/version.rb

Closes https://github.com/jekyll/github-metadata/issues/169.

Release 💎 v2.13.0

---

.gitignore

Resolve jekyll/github-metadata#199
Jekyll 4.x generates a cache when running the test suite. Prevent accidental commits.

Git-ignore the Jekyll cache.

---

docs/README.md
docs/development.md

docs: Add dev docs

---

docs/configuration.md

This PR sets the `PAGES_GITHUB_HOSTNAME` example to `github.com` without the protocol as GitHub pages also sets the `site.github.hostname` without the protocol.

set PAGES_GITHUB_HOSTNAME to hostname without protocol

---

lib/jekyll-github-metadata/repository.rb
spec/integration_spec.rb
spec/spec_helpers/stub_helper.rb

For each public repository rendered, we will also list releases for them.
Fixes #221.

Add site.github.public_repositories[].releases

---

docs/configuration.md

Why
===
In order to find out the logic to configure NWO using `git remote` depends on `JEKYLL_ENV` easily.
What
===
I got the errors when I ran `JEKYLL_ENV=production bundle exec jekyll serve` for GitHub Pages.
The error is something like this.
```
Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/single.html
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
```
When I checked this code, I figured out that `git remote` is only …

Add JEKYLL_ENV limitation for git remote

---

lib/jekyll-github-metadata/site_github_munger.rb
spec/site_github_munger_spec.rb

Jekyll 4 has a call to `site.config.inspect`, which renders all the values in `site.config['github']`.
This causes all of the API calls to be resolved regardless of whether the user is using them.
This patch should allow Jekyll 4 to call `site.config.inspect` without causing the large number of API calls.
Fixes #237.

Inject `site.github` via `:pre_render` step rather than `:after_init`

---

.rubocop.yml
jekyll-github-metadata.gemspec
lib/jekyll-github-metadata/client.rb
lib/jekyll-github-metadata/repository_finder.rb
spec/edit_link_tag_spec.rb
spec/metadata_drop_spec.rb

I'm opening this PR in the hopes of helping move along a new release of `github-metadata`.
This has the same version bump of `rubocop-jekyll` as #251 but I also went ahead and let rubocop autocorrect the formatting issues it found.

Bump rubocop-jekyll to 0.13.0 and fix rubocop issues

---

History.markdown
docs/configuration.md
lib/jekyll-github-metadata/client.rb
spec/client_spec.rb

We use [Nix](https://nixos.org/) to build our [project](https://github.com/VariantSync/DiffDetective) reproducibly, including the github-pages documentation. [This setup](https://github.com/VariantSync/DiffDetective/blob/07756a1b6c3b89049ba04d4980a220c499fc7f36/default.nix#L96) is also used in our [CI](https://github.com/VariantSync/DiffDetective/blob/07756a1b6c3b89049ba04d4980a220c499fc7f36/.github/workflows/maven.yml#L26) to build the github-pages which are eventually deployed. Nix prohibits network connections (except if the output hash is specified, which is unpractical in this case) because the network is not reproducible. However, in some circumstances (e.g., the default installation on macOS) the Nix sandbox is disabled or weakened. Hence, github-metadata accesses the network which …

Allow disabling of all network accesses
